sudo: required
language: node_js
notification: 
  email: thiago.vps20@gmail.com
node_js: 
  - 8.11.1
services: 
  - postgresql
env:
  gloabal:
    - NODE_ENV: integration
    - TRAVIS: true
addons:
  postgresql: '9.4'
before_script:
  - psql -c 'create database ts_api_test;' -U postgres
  - npm i -g sequelize-cli gulp-cli
  - cd src/
  - sequelize db:migrate --env test
  - npm install
  - gulp
script:
  - npm run unit-test-travis
  - npm run integration-test-travis